<?php
/**
 * CampaignStatus
 *
 * PHP version 5
 *
 * @category Class
 * @package  Boostapp
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Boost App Store API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@boostapp.store
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.13
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Boostapp\Model;
use \Boostapp\ObjectSerializer;

/**
 * CampaignStatus Class Doc Comment
 *
 * @category Class
 * @description It specifies the campaign status.
 * 0: Active
 * 1: Finished
 * 2: Review action (Not active)
 * 3: Review action finished (Not active)
 * 4: Compensating (Disabled)
 * 5: Compensation Finished (Disabled)
 * 6: Stopped
 * @package  Boostapp
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CampaignStatus
{
    /**
     * Possible values of this enum
     */
    const RUNNING = 0;
    const FINISH = 1;
    const IN_REVIEW = 2;
    const FINISH_REVIEW = 3;
    const IN_COMPENSE = 4;
    const FINISH_COMPENSE = 5;
    const STOPPING = 6;
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::RUNNING,
            self::FINISH,
            self::IN_REVIEW,
            self::FINISH_REVIEW,
            self::IN_COMPENSE,
            self::FINISH_COMPENSE,
            self::STOPPING,
        ];
    }
}


