<?php
/**
 * DeliveryType
 *
 * PHP version 5
 *
 * @category Class
 * @package  Boostapp
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Boost App Store API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@boostapp.store
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.13
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Boostapp\Model;
use \Boostapp\ObjectSerializer;

/**
 * DeliveryType Class Doc Comment
 *
 * @category Class
 * @description 0: Distribute operations for 24 hours
 * 1: Send fast
 * @package  Boostapp
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 * DeliveryType Class Doc Comment
 *
 * @category Class
 * @description
 * 0: İşlemleri 24 saate dağıt
 * 1: Hızlı gönderim yap
 * @package  reseller
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DeliveryType
{
    /**
     * Possible values of this enum
     */
    const SPREAD_IN_DAY = 0;
    const IMMEDIATE = 1;

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::SPREAD_IN_DAY,
            self::IMMEDIATE,
        ];
    }
}


