<?php
/**
 * InstallFrequency
 *
 * PHP version 5
 *
 * @category Class
 * @package  Boostapp
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Boost App Store API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@boostapp.store
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.13
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Boostapp\Model;
use \Boostapp\ObjectSerializer;

/**
 * InstallFrequency Class Doc Comment
 *
 * @category Class
 * @description It expresses the time difference between those transactions.
 *
 * 0: NULL value, DO NOT USE!
 * 1: Operations speed up over time
 * 2: Operations accelerate first then slow down
 * 3: Operations continue at constant speed
 * @package  Boostapp
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class InstallFrequency
{
    /**
     * Possible values of this enum
     */
    const NULLABLE = 0;
    const RISING = 1;
    const LINEAR = 2;
    const STATICAL = 3;
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::NULLABLE,
            self::RISING,
            self::LINEAR,
            self::STATICAL,
        ];
    }
}


