<?php
/**
 * Language
 *
 * PHP version 5
 *
 * @category Class
 * @package  Boostapp
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Boost App Store API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@boostapp.store
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.13
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Boostapp\Model;
use \Boostapp\ObjectSerializer;

/**
 * Language Class Doc Comment
 *
 * @category Class
 * @description Language list.
 * 1: EN
 * 2: TR
 * 3: RU
 * 4: FR
 * 5: JP
 * 6: KO
 * 7: PT
 * 8: DE
 * 9: IT
 * 10: ES
 * @package  Boostapp
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class Language
{
    /**
     * Possible values of this enum
     */
    const EN = 1;
    const TR = 2;
    const RU = 3;
    const FR = 4;
    const JP = 5;
    const KO = 6;
    const PT = 7;
    const DE = 8;
    const IT = 9;
    const ES = 10;

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::EN,
            self::TR,
            self::RU,
            self::FR,
            self::JP,
            self::KO,
            self::PT,
            self::DE,
            self::IT,
            self::ES,
        ];
    }
}


