<?php
/**
 * PurchaseLogType
 *
 * PHP version 5
 *
 * @category Class
 * @package  Boostapp
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Boost App Store API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@boostapp.store
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.13
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Boostapp\Model;
use \Boostapp\ObjectSerializer;

/**
 * PurchaseLogType Class Doc Comment
 *
 * @category Class
 * @description It specifies the type of purchase record
 * 0: After creating a campaign
 * 1: After posting comments (Not included in the API)
 * -1: Pay back
 * @package  Boostapp
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PurchaseLogType
{
    /**
     * Possible values of this enum
     */
    const CREATE_CAMPAIGN = 0;
    const REVIEW_SEND = 1;
    const REFUND = -1;

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::CREATE_CAMPAIGN,
            self::REVIEW_SEND,
            self::REFUND,
        ];
    }
}


