<?php
/**
 * CampaignCreateRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Boostapp
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Boost App Store API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@boostapp.store
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.13
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Boostapp;

/**
 * CampaignCreateRequestTest Class Doc Comment
 *
 * @category    Class
 * @description Campaign request model,
 * @package     Boostapp
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CampaignCreateRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CampaignCreateRequest"
     */
    public function testCampaignCreateRequest()
    {
    }

    /**
     * Test attribute "identifier"
     */
    public function testPropertyIdentifier()
    {
    }

    /**
     * Test attribute "package_name"
     */
    public function testPropertyPackageName()
    {
    }

    /**
     * Test attribute "country_id"
     */
    public function testPropertyCountryId()
    {
    }

    /**
     * Test attribute "days"
     */
    public function testPropertyDays()
    {
    }

    /**
     * Test attribute "five_star"
     */
    public function testPropertyFiveStar()
    {
    }

    /**
     * Test attribute "four_star"
     */
    public function testPropertyFourStar()
    {
    }

    /**
     * Test attribute "three_star"
     */
    public function testPropertyThreeStar()
    {
    }

    /**
     * Test attribute "two_star"
     */
    public function testPropertyTwoStar()
    {
    }

    /**
     * Test attribute "one_star"
     */
    public function testPropertyOneStar()
    {
    }

    /**
     * Test attribute "delivery_type"
     */
    public function testPropertyDeliveryType()
    {
    }

    /**
     * Test attribute "reviews"
     */
    public function testPropertyReviews()
    {
    }
}
