<?php
/**
 * CampaignDetailsRowTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Boostapp
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Boost App Store API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@boostapp.store
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.13
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Boostapp;

/**
 * CampaignDetailsRowTest Class Doc Comment
 *
 * @category    Class
 * @description CampaignDetailsRow
 * @package     Boostapp
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CampaignDetailsRowTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CampaignDetailsRow"
     */
    public function testCampaignDetailsRow()
    {
    }

    /**
     * Test attribute "day"
     */
    public function testPropertyDay()
    {
    }

    /**
     * Test attribute "row"
     */
    public function testPropertyRow()
    {
    }

    /**
     * Test attribute "keyword"
     */
    public function testPropertyKeyword()
    {
    }

    /**
     * Test attribute "fail_keyword_installs"
     */
    public function testPropertyFailKeywordInstalls()
    {
    }

    /**
     * Test attribute "fail_package_installs"
     */
    public function testPropertyFailPackageInstalls()
    {
    }

    /**
     * Test attribute "fail_reviews"
     */
    public function testPropertyFailReviews()
    {
    }

    /**
     * Test attribute "remaining_package_installs"
     */
    public function testPropertyRemainingPackageInstalls()
    {
    }

    /**
     * Test attribute "remaining_keyword_installs"
     */
    public function testPropertyRemainingKeywordInstalls()
    {
    }

    /**
     * Test attribute "remaining_reviews"
     */
    public function testPropertyRemainingReviews()
    {
    }

    /**
     * Test attribute "success_keyword_installs"
     */
    public function testPropertySuccessKeywordInstalls()
    {
    }

    /**
     * Test attribute "success_package_installs"
     */
    public function testPropertySuccessPackageInstalls()
    {
    }

    /**
     * Test attribute "success_reviews"
     */
    public function testPropertySuccessReviews()
    {
    }
}
