<?php
/**
 * CampaignCreateInfoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Boostapp
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Boost App Store API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@boostapp.store
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.13
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Boostapp;

/**
 * CampaignCreateInfoTest Class Doc Comment
 *
 * @category    Class
 * @description CampaignCreateInfo
 * @package     Boostapp
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CampaignCreateInfoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CampaignCreateInfo"
     */
    public function testCampaignCreateInfo()
    {
    }

    /**
     * Test attribute "campaign_id"
     */
    public function testPropertyCampaignId()
    {
    }

    /**
     * Test attribute "old_balance"
     */
    public function testPropertyOldBalance()
    {
    }

    /**
     * Test attribute "current_balance"
     */
    public function testPropertyCurrentBalance()
    {
    }

    /**
     * Test attribute "total_spend"
     */
    public function testPropertyTotalSpend()
    {
    }

    /**
     * Test attribute "package_install_price"
     */
    public function testPropertyPackageInstallPrice()
    {
    }

    /**
     * Test attribute "keyword_install_price"
     */
    public function testPropertyKeywordInstallPrice()
    {
    }

    /**
     * Test attribute "review_price"
     */
    public function testPropertyReviewPrice()
    {
    }

    /**
     * Test attribute "package_install_count"
     */
    public function testPropertyPackageInstallCount()
    {
    }

    /**
     * Test attribute "keyword_install_count"
     */
    public function testPropertyKeywordInstallCount()
    {
    }

    /**
     * Test attribute "review_count"
     */
    public function testPropertyReviewCount()
    {
    }

    /**
     * Test attribute "package_install_amount"
     */
    public function testPropertyPackageInstallAmount()
    {
    }

    /**
     * Test attribute "keyword_install_amount"
     */
    public function testPropertyKeywordInstallAmount()
    {
    }

    /**
     * Test attribute "review_amount"
     */
    public function testPropertyReviewAmount()
    {
    }
}
