<?php
/**
 * CampaignRowTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Boostapp
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Boost App Store API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@boostapp.store
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.13
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Boostapp;

/**
 * CampaignRowTest Class Doc Comment
 *
 * @category    Class
 * @description The model used to make multiple operations on the same day.
 * @package     Boostapp
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CampaignRowTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CampaignRow"
     */
    public function testCampaignRow()
    {
    }

    /**
     * Test attribute "frequency"
     */
    public function testPropertyFrequency()
    {
    }

    /**
     * Test attribute "install_count"
     */
    public function testPropertyInstallCount()
    {
    }

    /**
     * Test attribute "search_by"
     */
    public function testPropertySearchBy()
    {
    }

    /**
     * Test attribute "review_count"
     */
    public function testPropertyReviewCount()
    {
    }

    /**
     * Test attribute "review_delay"
     */
    public function testPropertyReviewDelay()
    {
    }
}
