<?php
/**
 * CountryTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Boostapp
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Boost App Store API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@boostapp.store
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.13
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Boostapp;

/**
 * CountryTest Class Doc Comment
 *
 * @category    Class
 * @description Country list.&lt;br&gt;1: US&lt;br&gt;2: TR&lt;br&gt;3: RU&lt;br&gt;4: IN&lt;br&gt;5: GB&lt;br&gt;6: FR&lt;br&gt;7: AU&lt;br&gt;8: JP&lt;br&gt;9: KR&lt;br&gt;10: BR&lt;br&gt;11: DE&lt;br&gt;12: CA&lt;br&gt;13: ES&lt;br&gt;14: PT&lt;br&gt;15: IT&lt;br&gt;16: NG
 * @package     Boostapp
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CountryTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Country"
     */
    public function testCountry()
    {
    }
}
