<?php
/**
 * LanguageTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Boostapp
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Boost App Store API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@boostapp.store
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.13
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Boostapp;

/**
 * LanguageTest Class Doc Comment
 *
 * @category    Class
 * @description Language list.&lt;br&gt;1: EN&lt;br&gt;2: TR&lt;br&gt;3: RU&lt;br&gt;4: FR&lt;br&gt;5: JP&lt;br&gt;6: KO&lt;br&gt;7: PT&lt;br&gt;8: DE&lt;br&gt;9: IT&lt;br&gt;10: ES
 * @package     Boostapp
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class LanguageTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Language"
     */
    public function testLanguage()
    {
    }
}
