<?php
/**
 * PurchaseLogTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Boostapp
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Boost App Store API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@boostapp.store
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.13
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Boostapp;

/**
 * PurchaseLogTest Class Doc Comment
 *
 * @category    Class
 * @description PurchaseLog
 * @package     Boostapp
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PurchaseLogTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PurchaseLog"
     */
    public function testPurchaseLog()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "customer_identifier"
     */
    public function testPropertyCustomerIdentifier()
    {
    }

    /**
     * Test attribute "package_name"
     */
    public function testPropertyPackageName()
    {
    }

    /**
     * Test attribute "campaign_id"
     */
    public function testPropertyCampaignId()
    {
    }

    /**
     * Test attribute "country_id"
     */
    public function testPropertyCountryId()
    {
    }

    /**
     * Test attribute "log_type"
     */
    public function testPropertyLogType()
    {
    }

    /**
     * Test attribute "package_installs"
     */
    public function testPropertyPackageInstalls()
    {
    }

    /**
     * Test attribute "keyword_installs"
     */
    public function testPropertyKeywordInstalls()
    {
    }

    /**
     * Test attribute "reviews"
     */
    public function testPropertyReviews()
    {
    }

    /**
     * Test attribute "package_install_price"
     */
    public function testPropertyPackageInstallPrice()
    {
    }

    /**
     * Test attribute "keyword_install_price"
     */
    public function testPropertyKeywordInstallPrice()
    {
    }

    /**
     * Test attribute "review_price"
     */
    public function testPropertyReviewPrice()
    {
    }

    /**
     * Test attribute "total_package_install_price"
     */
    public function testPropertyTotalPackageInstallPrice()
    {
    }

    /**
     * Test attribute "total_keyword_install_price"
     */
    public function testPropertyTotalKeywordInstallPrice()
    {
    }

    /**
     * Test attribute "total_review_price"
     */
    public function testPropertyTotalReviewPrice()
    {
    }

    /**
     * Test attribute "old_balance"
     */
    public function testPropertyOldBalance()
    {
    }

    /**
     * Test attribute "new_balance"
     */
    public function testPropertyNewBalance()
    {
    }

    /**
     * Test attribute "created"
     */
    public function testPropertyCreated()
    {
    }
}
