<?php
/**
 * ApplicationApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Boostapp
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Boost App Store API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@boostapp.store
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.13
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Boostapp;

use \Boostapp\Configuration;
use \Boostapp\ApiException;
use \Boostapp\ObjectSerializer;

/**
 * ApplicationApiTest Class Doc Comment
 *
 * @category Class
 * @package  Boostapp
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ApplicationApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for applicationAdd
     *
     * Adding.
     *
     */
    public function testApplicationAdd()
    {
    }

    /**
     * Test case for applicationInfo
     *
     * Details.
     *
     */
    public function testApplicationInfo()
    {
    }

    /**
     * Test case for applicationList
     *
     * Listing.
     *
     */
    public function testApplicationList()
    {
    }

    /**
     * Test case for applicationProducts
     *
     * Products.
     *
     */
    public function testApplicationProducts()
    {
    }
}
